[package]
name = "exercise-1"
version = "0.1.0"
authors = ["achim koh <3594463+achimkoh@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
